# Generated by Django 4.0.4 on 2022-05-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id_Ca', models.IntegerField(primary_key=True, serialize=False)),
                ('nomCategorie', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id_Co', models.IntegerField(primary_key=True, serialize=False)),
                ('referenceCmd', models.CharField(max_length=20)),
                ('dateCmd', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id_P', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('refProduit', models.CharField(max_length=20)),
                ('nomProduit', models.CharField(max_length=20)),
                ('dateProduction', models.DateField()),
                ('prix', models.IntegerField()),
            ],
        ),
    ]
