# Generated by Django 4.0.4 on 2022-05-04 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ouakki_ayoub', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commande',
        ),
        migrations.DeleteModel(
            name='Personne',
        ),
    ]
