# Generated by Django 4.0.4 on 2022-05-04 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ouakki_ayoub', '0002_delete_commande_delete_personne'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id_Co', models.IntegerField(primary_key=True, serialize=False)),
                ('referenceCmd', models.CharField(max_length=20)),
                ('dateCmd', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id_P', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('comnd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ouakki_ayoub.commande')),
            ],
        ),
    ]
