# Generated by Django 4.0.4 on 2022-05-05 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ouakki_ayoub', '0003_commande_personne'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categorie',
        ),
        migrations.DeleteModel(
            name='Produit',
        ),
    ]
