# Generated by Django 4.0.4 on 2022-05-05 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ouakki_ayoub', '0004_delete_categorie_delete_produit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('refProduit', models.CharField(max_length=20)),
                ('nomProduit', models.CharField(max_length=20)),
                ('dateProduction', models.DateField()),
                ('prix', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id_Ca', models.IntegerField(primary_key=True, serialize=False)),
                ('nomCategorie', models.CharField(max_length=20)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ouakki_ayoub.produit')),
            ],
        ),
    ]
