# Generated by Django 4.0.4 on 2022-05-05 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ouakki_ayoub', '0005_produit_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personne',
            name='comnd',
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
        migrations.DeleteModel(
            name='Commande',
        ),
        migrations.DeleteModel(
            name='Personne',
        ),
        migrations.DeleteModel(
            name='Produit',
        ),
    ]
