# Generated by Django 4.0.4 on 2022-05-05 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ouakki_ayoub', '0006_remove_personne_comnd_delete_categorie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id_Co', models.IntegerField(primary_key=True, serialize=False)),
                ('referenceCmd', models.CharField(max_length=20)),
                ('dateCmd', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('refProduit', models.CharField(max_length=20)),
                ('nomProduit', models.CharField(max_length=20)),
                ('dateProduction', models.DateField()),
                ('prix', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id_P', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('comnd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ouakki_ayoub.commande')),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ouakki_ayoub.produit'),
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id_Ca', models.IntegerField(primary_key=True, serialize=False)),
                ('nomCategorie', models.CharField(max_length=20)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ouakki_ayoub.produit')),
            ],
        ),
    ]
