# Generated by Django 4.0.4 on 2022-05-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouakki_ayoub', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.FloatField(),
        ),
    ]
