# Generated by Django 4.0.4 on 2022-05-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouakki_ayoub', '0008_alter_produit_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='cat',
            field=models.CharField(default='something', max_length=20),
        ),
    ]
