# Generated by Django 4.0.4 on 2022-05-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouakki_ayoub', '0009_produit_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='cat',
            field=models.CharField(default='No cat', max_length=20),
        ),
    ]
