# Generated by Django 4.0.4 on 2022-05-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouakki_ayoub', '0010_alter_produit_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='refc',
            field=models.CharField(default='no commande', max_length=20),
        ),
        migrations.AddField(
            model_name='personne',
            name='pe',
            field=models.CharField(default='no client', max_length=20),
        ),
    ]
