# Generated by Django 4.0.4 on 2022-05-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouakki_ayoub', '0011_commande_refc_personne_pe'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='datec',
            field=models.CharField(default='no commande', max_length=20),
        ),
    ]
