# Generated by Django 4.0.4 on 2022-05-08 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ouakki_ayoub', '0012_commande_datec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='comnd',
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
        migrations.DeleteModel(
            name='Commande',
        ),
        migrations.DeleteModel(
            name='Personne',
        ),
        migrations.DeleteModel(
            name='Produit',
        ),
    ]
