# Generated by Django 4.0.4 on 2022-05-08 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ouakki_ayoub', '0014_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='datec',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='refc',
        ),
    ]
