# Generated by Django 4.0.4 on 2022-05-08 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ouakki_ayoub', '0015_remove_commande_datec_remove_commande_refc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='comnd',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='categorie',
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
        migrations.DeleteModel(
            name='Commande',
        ),
        migrations.DeleteModel(
            name='Personne',
        ),
        migrations.DeleteModel(
            name='Produit',
        ),
    ]
