# Generated by Django 4.0.4 on 2022-05-08 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ouakki_ayoub', '0017_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='pers',
            new_name='client',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='pe',
        ),
    ]
